// @ts-nocheck
/* eslint-disable quotes */

export const _NFT2 = [
  {
    uri: 'QmP1W4iS9ymHpj71E8kStVmupXvc9wppG8DtGJraL2iV4u',
    name: 'Hector Hernandez',
    profession: 'Contrabandist',
    skills: 'Damage, Speed',
    image: 'ipfs/Qmeu7o674fcS4GJq66Db9CeLMSdvmNa3UoAg2ZTy5sB41C',
  },
  {
    uri: 'QmRWX87NkvBqzaDSb3SsaYAKpmW4SxFCLapqyvdXq8ugiG',
    name: 'ZoJo',
    profession: 'Space Wrestler',
    skills: 'Health, Armor',
    image: 'ipfs/Qmb8LK8NqmFzQruDQeAQ978ox7ybCJwaErTFEWF5Xngqfh',
  },
  {
    uri: 'QmVS1Qoa8ZsHWdPTk1wfrb33JNXnkeCqLsUcDDzmDzb4Zr',
    name: 'Major Kroton',
    profession: 'Retired Soldier',
    skills: 'Damage, Health',
    image: 'ipfs/QmSiDzsXocVCoELDh91DdvHNqE6wfQnPqbAFYRpqK5Bbig',
  },
  {
    uri: 'QmcgZLvpikkYCiZQtWh7hnpEt2C48EAb2uZXRT3U8asvH6',
    name: 'Object No. 113',
    profession: 'None',
    skills: 'Health, Speed',
    image: 'ipfs/QmPsYdPvyEsrebU8de4nNhGLNJWxbvbwysdhUUnsyb1bjV',
  },
  {
    uri: 'QmNmmUNJiPx9K46XhJAdSb2jNuM3h5UHdzS74fHtRkA2g7',
    name: 'Lady Sunset',
    profession: 'Professional Killer',
    skills: 'Damage, Speed',
    image: 'ipfs/QmVDiogds8dWLSuUQaUWgqGCktYxFMSyixEQ33wy1u9WvR',
  },
  {
    uri: 'Qmeuhn5c8YzQCLTzMHYRHYjUC4TgQsyzoVDtTDgDMYfD7X',
    name: 'Mister Poo',
    profession: 'Illegal Weapons Engineer',
    skills: 'Damage, Armor',
    image: 'ipfs/QmP5DWd77HQVsPbupQWZY6z9Zk3nrpnqipAhfCosbDaUqB',
  },
  {
    uri: 'QmegNF3udvjM8GWDPjadKfmKjGciDuEyZwH6mi5oRticSY',
    name: 'Tony Masfant',
    profession: 'Spaceship Commander',
    skills: 'Speed, Armor',
    image: 'ipfs/QmPwyrY9yzt6C3EzWdRuGHD1GMKueQKnRwvXYmCJzZPiuL',
  },
  {
    uri: 'QmXktQuvkLEMY2D1fKMMUyxAQFmDJDUGnVnYGTDHDnokL9',
    name: 'Jesse Сannibal',
    profession: 'Doctor',
    skills: 'Health, Speed',
    image: 'ipfs/QmQPAQtjZBaMJsx3sh9tsV9geAgpLf1GUBbyq5ehBbhVVn',
  },
  {
    uri: 'QmcWHkmZHhhNDQ5VxiyjucqVMEhoV9V6d7YyvDmWfRK9wC',
    name: 'Nitrine Spark',
    profession: 'Traveler',
    skills: 'Health, Speed',
    image: 'ipfs/Qmc7hnngKgzfT3DwgQxkZV3eDDsFYpGFgfTLmyXqfgCU5k',
  },
  {
    uri: 'Qmf7yG6AwEtXpDjEUrR9fFvuxiyzF2aGmQ7SB5vzTRi7Wf',
    name: "Robot 'Skeleton 11'",
    profession: 'Spaceship Guardian',
    skills: 'Health, Armor',
    image: 'ipfs/QmXKK7h7EfuYiEkcRnwWHi8Ju9wsXB8AhahrXF9qeWsGwb',
  },
  {
    uri: 'QmcKZhQdPWjLAUUfL1iBRSutc5zt5wG4pgnHy2vXZMYtvx',
    name: 'Alfred Constanta',
    profession: 'Physicist Warlock',
    skills: 'Damage, Health',
    image: 'ipfs/QmcQdqWKMtbhsGPUeVTmiDQmkfmo2peQ6S4jBVQYzHTyfD',
  },
  {
    uri: 'QmQnjXAkoF3qHM3hFDCmqE3JpBHTVK94wHAyTCvmxhxqAb',
    name: 'Christopher McKnill',
    profession: 'Legendary Astronaut',
    skills: 'Damage,Health, Armor',
    image: 'ipfs/QmPH57JXcPZQY8WKwToy2XUAtTrrpUA7BR2LMa2JRfRAnt',
  },
  {
    uri: 'QmQnjXAkoF3qHM3hFDCmqE3JpBHTVK94wHAyTCvmxhxqAb',
    name: 'Christopher McKnill',
    profession: 'Legendary Astronaut',
    skills: 'Damage,Health, Armor',
    image: 'ipfs/QmPH57JXcPZQY8WKwToy2XUAtTrrpUA7BR2LMa2JRfRAnt',
  },
];
